services:
  medicine-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-https://med.leandrosouza.info}
    ports:
      - '3050:3000'
    restart: unless-stopped
